# Start CanteenSys in Docker on LAN — shared DB at 192.168.153.248
param(
    [string]$LanIp = "192.168.120.51",
    [int]$Port = 365,
    [string]$DbHost = "192.168.153.248",
    [string]$DbUser = "sa",
    [string]$DbPassword = "@Mis#Dev",
    [string]$DbName = "CanteenManagementDB",
    [string]$SqlCmdContainer = "deploy-sqlserver-1",
    [string]$AnthropicKey = "",
    [string]$AnthropicModel = "claude-sonnet-5",
    [string]$GeminiKey = "",
    [string]$GeminiModel = "gemini-flash-lite-latest"
)

$ErrorActionPreference = "Stop"
$Deploy = $PSScriptRoot

if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
    throw "Docker not found. Install Docker Desktop first."
}

$envFile = Join-Path $Deploy ".env"
$csrf = @(
    "http://127.0.0.1:${Port}",
    "http://localhost:${Port}",
    "http://${LanIp}:${Port}",
    "http://192.168.153.248:${Port}"
) -join ","

@(
    "# Auto-generated by docker-start.ps1",
    "CMS_PORT=$Port",
    "DB_NAME=$DbName",
    "DB_USER=$DbUser",
    "DB_PASSWORD=$DbPassword",
    "DB_HOST=$DbHost",
    "DB_PORT=1433",
    "DB_DRIVER=ODBC Driver 18 for SQL Server",
    "DEBUG=False",
    "SECRET_KEY=cms-docker-lan-change-in-production",
    "ALLOWED_HOSTS=127.0.0.1,localhost,$LanIp,192.168.153.248",
    "CSRF_TRUSTED_ORIGINS=$csrf",
    "FORCE_SCRIPT_NAME=",
    "# POS voice LLM keys — fallback only; prefer DB (admin -> API integrations)",
    "ANTHROPIC_API_KEY=$AnthropicKey",
    "ANTHROPIC_MODEL=$AnthropicModel",
    "GEMINI_API_KEY=$GeminiKey",
    "GEMINI_MODEL=$GeminiModel"
) | Set-Content -Path $envFile -Encoding utf8

$baseUrl = "http://${LanIp}:${Port}"
$loginUrl = "${baseUrl}/users/login/"

Write-Host "=== CanteenSys Docker ===" -ForegroundColor Cyan
Write-Host "Shared SQL Server : ${DbHost} / ${DbName}" -ForegroundColor Green
Write-Host "LAN URL           : ${baseUrl}/" -ForegroundColor Green
Write-Host "Login             : $loginUrl" -ForegroundColor Green

Write-Host "Initializing database on ${DbHost} (if needed)..." -ForegroundColor Cyan
& (Join-Path $Deploy "init-db.ps1") `
    -SqlHost $DbHost `
    -SqlUser $DbUser `
    -SqlPassword $DbPassword `
    -SqlContainer $SqlCmdContainer

Write-Host "Building and starting container..." -ForegroundColor Cyan
Set-Location $Deploy
docker compose --env-file $envFile up -d --build

Write-Host ""
Write-Host "Done. Open $loginUrl" -ForegroundColor Green
Write-Host 'Default login: superadmin / Admin@123' -ForegroundColor Yellow
Write-Host "Note: local runserver and Docker share the same DB — run one at a time." -ForegroundColor Yellow
